### ISSUE TITLE
플레이어 점프 감지 관련 이슈

### ISSUE THREAD

**Issue by G-Nck** [GBKPM/Unity-Practice#3]
현재 점프 감지 로직:
조건 - 플레이어 오브젝트가 다른 오브젝트와 충돌 시작 시
실행 - 점프 중 여부를 false로 대입합니다.

문제점:
지형지물과 연관없는 오브젝트들과 충돌해도 '점프 중'이 false가 대입되며,
플레이어의 밑부분(발밑)이 아니라 다른 부분들이 닿아도 '점프 중'이 false가 대입됨.

**Comment by GBKPM** [comment]
해결완료
